namespace Kermalis.SoundFont2
{
	/// <summary>SF2 v2.1 spec page 38</summary>
	public enum SF2Generator : ushort
	{
		StartAddrsOffset = 0,
		EndAddrsOffset = 1,
		StartloopAddrsOffset = 2,
		EndloopAddrsOffset = 3,
		StartAddrsCoarseOffset = 4,
		ModLfoToPitch = 5,
		VibLfoToPitch = 6,
		ModEnvToPitch = 7,
		InitialFilterFc = 8,
		InitialFilterQ = 9,
		ModLfoToFilterFc = 10,
		ModEnvToFilterFc = 11,
		EndAddrsCoarseOffset = 12,
		ModLfoToVolume = 13,
		ChorusEffectsSend = 15,
		ReverbEffectsSend = 16,
		Pan = 17,
		DelayModLFO = 21,
		FreqModLFO = 22,
		DelayVibLFO = 23,
		FreqVibLFO = 24,
		DelayModEnv = 25,
		AttackModEnv = 26,
		HoldModEnv = 27,
		DecayModEnv = 28,
		SustainModEnv = 29,
		ReleaseModEnv = 30,
		KeynumToModEnvHold = 31,
		KeynumToModEnvDecay = 32,
		DelayVolEnv = 33,
		AttackVolEnv = 34,
		HoldVolEnv = 35,
		DecayVolEnv = 36,
		SustainVolEnv = 37,
		ReleaseVolEnv = 38,
		KeynumToVolEnvHold = 39,
		KeynumToVolEnvDecay = 40,
		Instrument = 41,
		KeyRange = 43,
		VelRange = 44,
		StartloopAddrsCoarseOffset = 45,
		Keynum = 46,
		Velocity = 47,
		InitialAttenuation = 48,
		EndloopAddrsCoarseOffset = 50,
		CoarseTune = 51,
		FineTune = 52,
		SampleID = 53,
		SampleModes = 54,
		ScaleTuning = 56,
		ExclusiveClass = 57,
		OverridingRootKey = 58,
		EndOper = 60,
	}
}
